version: '3'

services:
  web:
    container_name: 'dve_web'
    build: .
    volumes:
      - '.:/web'
    ports:
      - '3000:3000'
    command: 'npm run dev'
    tty: true
    stdin_open: true

  # sig:
  #   container_name: 'dve_sig'
  #   build: .
  #   volumes:
  #     - '.:/web'
  #   ports:
  #     - '3001:3001'
  #   command: 'node signaling/app.js'
  #   tty: true
  #   stdin_open: true
